/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OurExpertiseRouteImport } from './routes/our-expertise'
import { Route as LuxuryFinishesCoatingsRouteImport } from './routes/luxury-finishes-coatings'
import { Route as InteriorExteriorRestorationRenovationRouteImport } from './routes/interior-exterior-restoration-renovation'
import { Route as FenceServicesRouteImport } from './routes/fence-services'
import { Route as CustomWoodStructuresOutdoorDesignRouteImport } from './routes/custom-wood-structures-outdoor-design'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as IndexRouteImport } from './routes/index'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OurExpertiseRoute = OurExpertiseRouteImport.update({
  id: '/our-expertise',
  path: '/our-expertise',
  getParentRoute: () => rootRouteImport,
} as any)
const LuxuryFinishesCoatingsRoute = LuxuryFinishesCoatingsRouteImport.update({
  id: '/luxury-finishes-coatings',
  path: '/luxury-finishes-coatings',
  getParentRoute: () => rootRouteImport,
} as any)
const InteriorExteriorRestorationRenovationRoute =
  InteriorExteriorRestorationRenovationRouteImport.update({
    id: '/interior-exterior-restoration-renovation',
    path: '/interior-exterior-restoration-renovation',
    getParentRoute: () => rootRouteImport,
  } as any)
const FenceServicesRoute = FenceServicesRouteImport.update({
  id: '/fence-services',
  path: '/fence-services',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomWoodStructuresOutdoorDesignRoute =
  CustomWoodStructuresOutdoorDesignRouteImport.update({
    id: '/custom-wood-structures-outdoor-design',
    path: '/custom-wood-structures-outdoor-design',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact-us': typeof ContactUsRoute
  '/custom-wood-structures-outdoor-design': typeof CustomWoodStructuresOutdoorDesignRoute
  '/fence-services': typeof FenceServicesRoute
  '/interior-exterior-restoration-renovation': typeof InteriorExteriorRestorationRenovationRoute
  '/luxury-finishes-coatings': typeof LuxuryFinishesCoatingsRoute
  '/our-expertise': typeof OurExpertiseRoute
  '/privacy': typeof PrivacyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact-us': typeof ContactUsRoute
  '/custom-wood-structures-outdoor-design': typeof CustomWoodStructuresOutdoorDesignRoute
  '/fence-services': typeof FenceServicesRoute
  '/interior-exterior-restoration-renovation': typeof InteriorExteriorRestorationRenovationRoute
  '/luxury-finishes-coatings': typeof LuxuryFinishesCoatingsRoute
  '/our-expertise': typeof OurExpertiseRoute
  '/privacy': typeof PrivacyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact-us': typeof ContactUsRoute
  '/custom-wood-structures-outdoor-design': typeof CustomWoodStructuresOutdoorDesignRoute
  '/fence-services': typeof FenceServicesRoute
  '/interior-exterior-restoration-renovation': typeof InteriorExteriorRestorationRenovationRoute
  '/luxury-finishes-coatings': typeof LuxuryFinishesCoatingsRoute
  '/our-expertise': typeof OurExpertiseRoute
  '/privacy': typeof PrivacyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/contact-us'
    | '/custom-wood-structures-outdoor-design'
    | '/fence-services'
    | '/interior-exterior-restoration-renovation'
    | '/luxury-finishes-coatings'
    | '/our-expertise'
    | '/privacy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/contact-us'
    | '/custom-wood-structures-outdoor-design'
    | '/fence-services'
    | '/interior-exterior-restoration-renovation'
    | '/luxury-finishes-coatings'
    | '/our-expertise'
    | '/privacy'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/contact-us'
    | '/custom-wood-structures-outdoor-design'
    | '/fence-services'
    | '/interior-exterior-restoration-renovation'
    | '/luxury-finishes-coatings'
    | '/our-expertise'
    | '/privacy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  ContactUsRoute: typeof ContactUsRoute
  CustomWoodStructuresOutdoorDesignRoute: typeof CustomWoodStructuresOutdoorDesignRoute
  FenceServicesRoute: typeof FenceServicesRoute
  InteriorExteriorRestorationRenovationRoute: typeof InteriorExteriorRestorationRenovationRoute
  LuxuryFinishesCoatingsRoute: typeof LuxuryFinishesCoatingsRoute
  OurExpertiseRoute: typeof OurExpertiseRoute
  PrivacyRoute: typeof PrivacyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-expertise': {
      id: '/our-expertise'
      path: '/our-expertise'
      fullPath: '/our-expertise'
      preLoaderRoute: typeof OurExpertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/luxury-finishes-coatings': {
      id: '/luxury-finishes-coatings'
      path: '/luxury-finishes-coatings'
      fullPath: '/luxury-finishes-coatings'
      preLoaderRoute: typeof LuxuryFinishesCoatingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interior-exterior-restoration-renovation': {
      id: '/interior-exterior-restoration-renovation'
      path: '/interior-exterior-restoration-renovation'
      fullPath: '/interior-exterior-restoration-renovation'
      preLoaderRoute: typeof InteriorExteriorRestorationRenovationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fence-services': {
      id: '/fence-services'
      path: '/fence-services'
      fullPath: '/fence-services'
      preLoaderRoute: typeof FenceServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-wood-structures-outdoor-design': {
      id: '/custom-wood-structures-outdoor-design'
      path: '/custom-wood-structures-outdoor-design'
      fullPath: '/custom-wood-structures-outdoor-design'
      preLoaderRoute: typeof CustomWoodStructuresOutdoorDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  ContactUsRoute: ContactUsRoute,
  CustomWoodStructuresOutdoorDesignRoute:
    CustomWoodStructuresOutdoorDesignRoute,
  FenceServicesRoute: FenceServicesRoute,
  InteriorExteriorRestorationRenovationRoute:
    InteriorExteriorRestorationRenovationRoute,
  LuxuryFinishesCoatingsRoute: LuxuryFinishesCoatingsRoute,
  OurExpertiseRoute: OurExpertiseRoute,
  PrivacyRoute: PrivacyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
